language: swift
osx_image: xcode9.4

# environment variables
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8

addons:
  sonarcloud:
    organization: michaeltansg-github

# before_install:
#   - gem update --system
#   - gem install fastlane --no-rdoc --no-ri --no-document --quiet

script:
- fastlane ios coverage
- fastlane ios sonar_scan
