language: swift
osx_image: xcode9.4

# environment variables
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8

addons:
  sonarcloud:
    organization: michaeltansg-github

#before_install:
#  - brew update
#  - brew upgrade swiftlint
#  - brew outdated carthage || brew upgrade carthage
#  - carthage bootstrap --verbose --no-use-binaries --platform iOS,tvOS,watchOS --cache-builds
#  - gem update --system
#  - gem install fastlane --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -project ApplicationCoordinator.xcodeproj -scheme ApplicationCoordinator -sdk iphonesimulator -enableCodeCoverage YES -destination 'platform=iOS Simulator,id=487A5625-5224-4587-BF5D-B37B2B776849' ONLY_ACTIVE_ARCH=NO GCC_GENERATE_TEST_COVERAGE_FILES=YES test -derivedDataPath DerivedData | xcpretty
- xcrun llvm-cov show -instr-profile=$(find DerivedData -iname 'Coverage.profdata') DerivedData/Build/Products/Debug-iphonesimulator/ApplicationCoordinator.app/ApplicationCoordinator > DerivedData/Coverage.report
# - fastlane ios coverage && sonar-scanner
- sonar-scanner

# after_success:
# - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
