language: swift
osx_image: xcode9.4

# environment variables
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8

addons:
  sonarcloud:
    organization: michaeltansg-github

#before_install:
#  - brew update
#  - brew upgrade swiftlint
#  - brew outdated carthage || brew upgrade carthage
#  - carthage bootstrap --verbose --no-use-binaries --platform iOS,tvOS,watchOS --cache-builds
#  - gem update --system
#  - gem install fastlane --no-rdoc --no-ri --no-document --quiet

script:
# - set -o pipefail
# - xcodebuild test -project ApplicationCoordinator.xcodeproj -scheme ApplicationCoordinator -destination 'platform=iOS Simulator,id=5C60A3D8-62B9-439B-A45C-819CA646B356' ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty;
- fastlane ios coverage && sonar-scanner

# after_success:
# - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
