# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "ApplicationCoordinator",
      code_coverage: true
    )
  end

  desc "Runs coverage"
  lane :coverage do
    output_directory = 'fastlane/test_output'
    test
    slather(
      travis: true,
      scheme: "ApplicationCoordinator",
      # coveralls: true, # coveralls
      cobertura_xml: true, # sonar scanner
      output_directory: output_directory, # required for cobertura_xml, defaults to project root
      proj: "ApplicationCoordinator.xcodeproj"
    )
    # swiftlint(output_file: "#{output_directory}/swiftlint.txt", ignore_exit_status: true)
  end
end
